//
//  Constants.swift
//  Tour
//
//  Created by Ricketia Steele on 5/22/23.
//

import Foundation

struct Constants {
    static let montgomeryD = "Montgomery is the capital and the second most populated city in the state of Alabama.  This big city located in the south-central portion of the state of Alabama. As the birthplace of the Civil Rights Movement, the city was a major contribution to the history of the United States."
    static let montgomeryS = "The National Memorial for Peace and Justice"
    static let montgomeryF = "The National Memorial for Peace and Justice, informally known as the National Lynching Memorial, is a national memorial to commemorate the black victims of lynching in the United States. It is intended to focus on and acknowledge past racial terrorism and advocate for social justice in America.  The National Memorial for Peace and Justice, which opened to the public on April 26, 2018, is the nation’s first memorial dedicated to the legacy of enslaved Black people, people terrorized by lynching, African Americans humiliated by racial segregation and Jim Crow, and people of color burdened with contemporary presumptions of guilt and police violence."
    static let tuskegeeD = "Tuskegee is located in central Alabama near the city of Montgomery. It has been home to many nationally recognized figures. Rosa Parks was born there in 1913. The Commodores, who had a number of funk and soul hits during the 1970s and 1980s, met as students at Tuskegee University. Their lead singer, Lionel Ritchie, who later went on to considerable success as a solo act, attended Tuskegee on a tennis scholarship and graduated with a major in economics."
    static let tuskegeeS = "George Washington Carver Museum"
    static let tuskegeeF = "The Carver Museum was developed with substantial support from admirer and industrialist Henry Ford. Carver wanted the fruits of his life's work on display at the museum. He hoped that the exhibits would inspire children to live better lives."
    static let selmaD = "The city of Selma has been the epicenter of some of the most significant events and eras in Alabama history.  Selma became a locus of the civil rights movement with the establishment of an NAACP chapter and the Dallas County Voters League in the 1920s."
    static let selmaS = "Edmund Pettus Bridge"
    static let selmaF = "The Edmund Pettus Bridge carries U.S. Route 80 Business across the Alabama River in Selma, Alabama. Built in 1940, it is named after Edmund Pettus, a former Confederate brigadier general, U.S. senator, and state-level leader of the Alabama Ku Klux Klan. The city's iconic Edmund Pettus Bridge served as the stage for the movement's most infamous series of incidents as state and local police attacked marchers during their attempts to walk from Selma to Montgomery in March 1965."
    static let tuscaloosaD = "Located in west-central Alabama along the fall line and the Black Warrior River, the city of Tuscaloosa is the state’s fifth most populous city and is the county seat of Tuscaloosa County. The town is named after Tuskaloosa, leader of the Mississippian town of Mabila (also known as Mauvila) who was executed by Spanish explorer Hernando de Soto’s men in 1540. Tuscaloosa served as the state’s capital from 1826 to 1846 and has been home to the University of Alabama since 1831."
    static let tuscaloosaS = "Fosters Auditorium"
    static let tuscaloosaF = "Foster Auditorium is known as the site of the “Stand in the Schoolhouse Door” incident. On June 11, 1963, Governor George C. Wallace, making good on a campaign pledge to not allow integration of the university, stood in the doorway of the building on the day of registration. He was attempting to block two black students, Vivian Malone and James Hood, from enrolling at the university. PresidentJohn F. Kennedy called on the Alabama National Guard to forcibly allow the students to enter the building if need be. Calling it “an unwelcomed, unwanted, unwarranted and force-induced intrusion upon the campus,”Wallace denounced the actions, but, seeing as he could not win against the combined efforts of the Guard, federal marshals and Deputy United States Attorney General Nicholas Katzenbach, stepped aside, returning to the state capital as Malone and Hood entered for registration. The incident is seen as one of the seminal events in the Civil Rights Movement in America."
    static let huntsvilleD = "Huntsville, located in the northernmost part of Alabama near the Tennessee border, is the fourth largest city in the state and the seat of Madison County. As the first incorporated town in Alabama, Huntsville played an important part in the birth and growth of the state."
    static let huntsvilleS = "10th Cavalry Buffalo Soldier's Memorial"
    static let huntsvilleF = "In 1866, Congress passed legislation establishing two cavalry and two infantry regiments, whose enlisted composition was made up of African Americans, to serve in the United States Army. When war broke out in Spain on April 25, 1898, all four African-American regiments were recalled from the West. Arriving in Cuba on June 22,theBuffaloSoldiers participated in the battles of Las Guasimas, El Caney and San Juan Hill, winning six medals of honor for gallantry in action. After the war, three regiments remained on occupation duty while the 10th United States Cavalry was ordered to New York, then to Camp Albert G. Forse in Huntsville, Ala. From October 18 1898 until January 28, 1899, the U.S.10th Cavalry was encamped at this location, hence Cavalry Hills. Today, the memorial honors all African Americans who have served in all of the nation's wars."
    static let talladegaD = "Located in northeast central part of Alabama, approximately 50 miles east of Birmingham, the city of Talladega was incorporated in 1835. It is home to one of the nation’s most comprehensive educational programs for the deaf and blind, to Alabama’s oldest private historically black liberal arts college."
    static let talladegaS = "Amistand Murals"
    static let talladegaF = "The Amistad Murals consists of three panels depicting the Amistad Incident in which Joseph Cinque led a revolt on the Amistad that liberated a shipload of captive Africans. They are housed in the Dr. William R. Harvey Museum of Art on the campus of Talladega College. Artist Hale Aspacio Woodruff was commissioned to paint the murals in 1938 and they have become known as one of his best documented works."
}
